merge:
  image: node:8.9.4
  stage: test
  cache:
    paths:
      - node_modules/
  variables:
    PRINT_MR_IID_CMD: "import sys,json; print(json.load(sys.stdin)['iid'])"
    CREATE_MR_URL: "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/?source_branch=development&target_branch=master&title=Automatic%20merge%20from%20GitLab%20CI%20$CI_PIPELINE_ID"
  before_script:
    - npm install
  script:
    - MR_IID=$(curl --header "Private-Token:$PRIVATE_TOKEN" -X POST $CREATE_MR_URL | python -c "$PRINT_MR_IID_CMD")
    - ACCEPT_MR_URL="https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/merge?merge_when_pipeline_succeeds=true"
    - curl --header "Private-Token:$PRIVATE_TOKEN" -X PUT $ACCEPT_MR_URL
  only:
    - development
deploy-staging:
  image: node:8.9.4
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    REMOTE_USER: "musilitar"
    REMOTE_ADDRESS: "209.250.253.37"
    PATH_BUILDS: "/home/musilitar/builds/goautoscore"
    PATH_SCRIPTS: "/home/musilitar/scripts/goautoscore"
    PATH_INSTALL_SCRIPT: "$PATH_SCRIPTS/install.sh"
  before_script:
    - apt-get update -qq > /dev/null
    - apt-get install zip -qq > /dev/null
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mkdir dist
    - npm install
  script:
    - npm run install:staging
    - zip -r -j -q build-$CI_PIPELINE_ID.zip dist/*
    - scp install.sh $REMOTE_USER@$REMOTE_ADDRESS:$PATH_INSTALL_SCRIPT
    - scp build-$CI_PIPELINE_ID.zip $REMOTE_USER@$REMOTE_ADDRESS:$PATH_BUILDS
    - ssh $REMOTE_USER@$REMOTE_ADDRESS ". $PATH_INSTALL_SCRIPT $CI_PIPELINE_ID"
  only:
    - development
deploy-production:
  image: node:8.9.4
  stage: deploy
  cache:
    paths:
      - node_modules/
  variables:
    REMOTE_USER: "musilitar"
    REMOTE_ADDRESS: "45.76.38.194"
    PATH_BUILDS: "/home/musilitar/builds/goautoscore"
    PATH_SCRIPTS: "/home/musilitar/scripts/goautoscore"
    PATH_INSTALL_SCRIPT: "$PATH_SCRIPTS/install.sh"
  before_script:
    - apt-get update -qq > /dev/null
    - apt-get install zip -qq > /dev/null
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mkdir dist
    - npm install
  script:
    - npm run install:production
    - zip -r -j -q build-$CI_PIPELINE_ID.zip dist/*
    - scp install.sh $REMOTE_USER@$REMOTE_ADDRESS:$PATH_INSTALL_SCRIPT
    - scp build-$CI_PIPELINE_ID.zip $REMOTE_USER@$REMOTE_ADDRESS:$PATH_BUILDS
    - ssh $REMOTE_USER@$REMOTE_ADDRESS ". $PATH_INSTALL_SCRIPT $CI_PIPELINE_ID"
  only:
    - tags