[[redirects]]
from = "/api/*/authenticate"
to = "https://staging.generiekebackend.com/api/:splat/authenticate"
status = 200
force = true
headers = {API-key = "6f5dfb13-c9ec-47a9-8417-129506410658"}

[[redirects]]
from = "/api/*"
to = "https://staging.generiekebackend.com/api/:splat"
status = 200
force = true